from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('analytics/', views.analytics, name='analytics'),
    # Notes
    path('notes/', views.notes_list, name='notes_list'),
    path('notes/upload/', views.upload_note, name='upload_note'),
    path('notes/search/', views.search_notes, name='search_notes'),
    path('notes/<int:note_id>/', views.note_detail, name='note_detail'),
    path('notes/<int:note_id>/edit/', views.edit_note, name='edit_note'),
    path('notes/<int:note_id>/file/', views.note_file, name='note_file'),
    path('notes/<int:note_id>/attachments/add/', views.note_attachment_add, name='note_attachment_add'),
    path('note-attachments/<int:attachment_id>/file/', views.note_attachment_file, name='note_attachment_file'),
    path('note-attachments/<int:attachment_id>/delete/', views.note_attachment_delete, name='note_attachment_delete'),
    path('notes/<int:note_id>/delete/', views.delete_note, name='delete_note'),
    path('notes/trash/', views.trash_notes, name='trash_notes'),
    path('notes/<int:note_id>/restore/', views.restore_note, name='restore_note'),
    path('notes/<int:note_id>/delete-permanently/', views.delete_note_permanently, name='delete_note_permanently'),
    path('notes/export/csv/', views.export_notes_csv, name='export_notes_csv'),
    path('notes/export/json/', views.export_notes_json, name='export_notes_json'),
    path('notes/import/', views.import_notes, name='import_notes'),
    # Tasks
    path('tasks/', views.task_list, name='task_list'),
    path('tasks/add/', views.add_task, name='add_task'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/edit/<int:task_id>/', views.edit_task, name='edit_task'),
    path('task-comments/<int:comment_id>/delete/', views.task_comment_delete, name='task_comment_delete'),
    path('tasks/<int:task_id>/attachments/add/', views.task_attachment_add, name='task_attachment_add'),
    path('task-attachments/<int:attachment_id>/file/', views.task_attachment_file, name='task_attachment_file'),
    path('task-attachments/<int:attachment_id>/delete/', views.task_attachment_delete, name='task_attachment_delete'),
    path('tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('tasks/trash/', views.trash_tasks, name='trash_tasks'),
    path('tasks/<int:task_id>/restore/', views.restore_task, name='restore_task'),
    path('tasks/<int:task_id>/delete-permanently/', views.delete_task_permanently, name='delete_task_permanently'),
    path('tasks/export/csv/', views.export_tasks_csv, name='export_tasks_csv'),
    path('tasks/export/json/', views.export_tasks_json, name='export_tasks_json'),
    path('tasks/import/', views.import_tasks, name='import_tasks'),
    # Activity Log
    path('activity/log/', views.activity_log, name='activity_log'),
    # Calendar Integrations
    path('calendar/export/ical/', views.export_calendar_ical, name='export_calendar_ical'),
    path('calendar/instructions/', views.calendar_instructions, name='calendar_instructions'),

    # Study Recommendations
    path('recommendations/', views.study_recommendations, name='study_recommendations'),
    # Planner
    path('planner/', views.planner, name='planner'),
    path('planner/adaptive/', views.adaptive_planner, name='adaptive_planner'),
    path('planner/daily-schedule/', views.daily_schedule, name='daily_schedule'),
    path('planner/<int:plan_id>/edit/', views.study_plan_edit, name='study_plan_edit'),
    path('planner/<int:plan_id>/delete/', views.study_plan_delete, name='study_plan_delete'),
    path('planner/<int:plan_id>/restore/', views.study_plan_restore, name='study_plan_restore'),
    path('calendar/', views.calendar_view, name='calendar'),
    # Attendance
    path('attendance/', views.attendance, name='attendance'),
    path('attendance/report/', views.attendance_report, name='attendance_report'),
    path('attendance/teacher/', views.teacher_attendance, name='teacher_attendance'),
    path('teacher/students/', views.teacher_student_list, name='teacher_student_list'),
    path('teacher/reports/', views.teacher_progress_report, name='teacher_progress_report'),
    # Admin
    path('adminpanel/', views.admin_dashboard, name='admin_dashboard'),
    path('adminpanel/users/', views.manage_users, name='manage_users'),
    path('adminpanel/announcements/', views.announcements, name='announcements'),
    path('adminpanel/announcements/<int:announcement_id>/edit/', views.announcement_edit, name='announcement_edit'),
    path('adminpanel/announcements/<int:announcement_id>/delete/', views.announcement_delete, name='announcement_delete'),
    path('adminpanel/settings/', views.admin_settings, name='admin_settings'),
    path('adminpanel/settings/<int:setting_id>/delete/', views.admin_setting_delete, name='admin_setting_delete'),
    path('adminpanel/audit/', views.admin_audit_logs, name='admin_audit_logs'),
    # Normalized academic domain
    path('subjects/', views.subject_list, name='subject_list'),
    path('subjects/add/', views.subject_create, name='subject_create'),
    path('subjects/<int:subject_id>/edit/', views.subject_edit, name='subject_edit'),
    path('subjects/<int:subject_id>/archive/', views.subject_delete, name='subject_delete'),
    path('subjects/<int:subject_id>/topics/add/', views.topic_create, name='topic_create'),
    path('topics/<int:topic_id>/edit/', views.topic_edit, name='topic_edit'),
    path('topics/<int:topic_id>/delete/', views.topic_delete, name='topic_delete'),
    path('subjects/<int:subject_id>/teachers/', views.teacher_assignment_list, name='teacher_assignment_list'),
    path('teacher-assignments/<int:assignment_id>/remove/', views.teacher_assignment_delete, name='teacher_assignment_delete'),
    path('enrollments/', views.enrollment_list, name='enrollment_list'),
    path('enrollments/<int:enrollment_id>/remove/', views.enrollment_delete, name='enrollment_delete'),
    path('study-sessions/', views.study_session_list, name='study_session_list'),
    path('study-sessions/<int:session_id>/delete/', views.study_session_delete, name='study_session_delete'),
    path('goals/', views.goal_list, name='goal_list'),
    path('goals/<int:goal_id>/edit/', views.goal_edit, name='goal_edit'),
    path('goals/<int:goal_id>/delete/', views.goal_delete, name='goal_delete'),
    path('goals/<int:goal_id>/restore/', views.goal_restore, name='goal_restore'),
    path('exams/', views.exam_list, name='exam_list'),
    path('exams/add/', views.exam_create, name='exam_create'),
    path('exams/<int:exam_id>/edit/', views.exam_edit, name='exam_edit'),
    path('exams/<int:exam_id>/archive/', views.exam_delete, name='exam_delete'),
    path('exams/<int:exam_id>/restore/', views.exam_restore, name='exam_restore'),
    path('exams/<int:exam_id>/result/', views.exam_result_create, name='exam_result_create'),
    path(
        'exams/<int:exam_id>/results/',
        views.teacher_exam_results,
        name='teacher_exam_results',
    ),
    path(
        'exams/<int:exam_id>/students/<int:student_id>/result/',
        views.teacher_exam_result_edit,
        name='teacher_exam_result_edit',
    ),
    path('notifications/', views.notification_list, name='notification_list'),
    path('notifications/<int:notification_id>/read/', views.notification_mark_read, name='notification_mark_read'),
    path('achievements/', views.achievement_list, name='achievement_list'),
    path('planner/events/', views.planner_event_list, name='planner_event_list'),
    path('planner/events/<int:event_id>/edit/', views.planner_event_edit, name='planner_event_edit'),
    path('planner/events/<int:event_id>/reminders/add/', views.planner_event_reminder_add, name='planner_event_reminder_add'),
    path('planner/reminders/<int:reminder_id>/delete/', views.planner_event_reminder_delete, name='planner_event_reminder_delete'),
    path('planner/events/<int:event_id>/delete/', views.planner_event_delete, name='planner_event_delete'),
    path('planner/events/<int:event_id>/restore/', views.planner_event_restore, name='planner_event_restore'),
]