# Generated by Django 6.0.7 on 2026-09-12 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user'], name='idx_attendance_user'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='idx_attendance_date'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user'], name='idx_note_user'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='idx_note_created_at'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user'], name='idx_studyplan_user'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['date'], name='idx_studyplan_date'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='idx_task_user'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='idx_task_due_date'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='idx_task_created_at'),
        ),
    ]
