# Generated by Django 6.0.7 on 2026-09-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0010_academic_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DEADLINE', 'Deadline'), ('REMINDER', 'Reminder'), ('ATTENDANCE', 'Attendance'), ('GOAL', 'Goal'), ('STREAK', 'Streak'), ('ACHIEVEMENT', 'Achievement'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
    ]
