# Generated by Django 6.0.7 on 2026-09-13 11:46

import django.db.models.deletion
from django.db import migrations, models


def populate_attendance_status(apps, schema_editor):
    Attendance = apps.get_model('studyapp', 'Attendance')
    Attendance.objects.filter(status__isnull=True, is_present=True).update(status='PRESENT')
    Attendance.objects.filter(status__isnull=True, is_present=False).update(status='ABSENT')


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0012_planner_event_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='studyapp.subject'),
        ),
        migrations.RunPython(populate_attendance_status, migrations.RunPython.noop),
    ]
