# Generated by Django 6.0.7 on 2026-09-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0013_attendance_status_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
