# Generated by Django 6.0.7 on 2026-09-13 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0014_studyplan_deleted_at_studyplan_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['subject', 'is_archived', 'exam_date'], name='studyapp_ex_subject_0995f4_idx'),
        ),
    ]
